{% set name = "libmobility" %}
{% set version = "1.1.0" %}

{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/stochasticHydroTools/libMobility/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 43e664d6edb23353af976953d860b90ab081de2ccac8bb6d2d660fa42c185d5a
  - url: https://github.com/RaulPPelaez/UAMMD/archive/refs/tags/v3.0.0.tar.gz
    sha256: 61af3ba221b9d4804955594bd73e54d1c4a793f2c7e33373b3cce148f7ab77b1
    folder: uammd-src

build:
  skip: true  # [win or not (cuda_compiler_version or "").startswith("12")]
  # Debugging skips
  # skip: true  # [py != 312]
  number: 0
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  rpaths:
    - lib/
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux64]
  ignore_run_exports_from:
    - libcusolver-dev
    - libcurand-dev

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - make
    - cmake >=3.25.2
    - numpy                                  # [build_platform != target_platform]
    - nomkl                                  # [build_platform != target_platform]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - numpy
    - cuda-version {{ cuda_compiler_version }}
    - cuda-cudart-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libblas
    - libcblas  # has header files for libblas
    - liblapacke
    - nanobind
  run:
    - python

test:
  requires:
    - pytest
    - scipy
    # Prove that netlib-linked BLAS works with MKL
    - libblas * *mkl  # [x86 or x86_64]
  imports:
    - libMobility
  source_files:
    - tests
  commands:
    - pytest -vs -k SelfMobility tests/test_*py

about:
  home: https://github.com/stochasticHydroTools/libmobility
  license: MIT
  license_file: LICENSE
  summary: Compute the action of the hydrodynamic mobility (at the RPY/FCM level) of a group of particles (in different geometries) with forces acting on them. Requires a CUDA compatible GPU.

extra:
  recipe-maintainers:
    - rykerfish
    - brennansprinkle
    - RaulPPelaez
